### ISSUE TITLE
New to node.js; love the demo; miss the documentation

### ISSUE THREAD

**Issue by enginpost** [0x73746F66/node-rest-demo#1]
I found this through your blog. I can follow most of it, but get a little lost on some of the lines. Is there any chance at some point you might add some comments to the code (to explain whatever the next line is trying to do)?

-- please, feel free to remove this. It is obviously not an issue, but a request, if you happen to have time to do it --

**Comment by chrisdlangton** [comment]
First of all, sorry for the delay - I wasnt aware this was active on Github!

I'll open it up in my IDE today and keep it open until i update the source code and check it in.

You know those moments you look back on code you wrote months/years ago ago and think to yourself its written without the standards you have now? I want to go back and fix this :)
