### ISSUE TITLE
Demo password

### ISSUE THREAD

**Issue by snacky6** [0x73746F66/node-rest-demo#2]
First of all, thank you for this demo, it's very useful!
I'm having some issues while trying to use the app. I noticed that the server is secured with a username and a password (the development environment username seams to be "clangton") but I can't find a way to use or change the password as it's "aes-256-cbc" encryption with some base64 related stuff... 

I really need your help on this point :/

Thanks!

**Comment by chrisdlangton** [comment]
@snacky6 
For your purposes you set your own username, replace clangton.
The password is stored in the database for the user when you create the user record - you do not get the database from anyone on Github ever, you need to install your own for all your code.

For the purposes of the DEMO I have provided some SQL to create the tables you need, so the first thing you need to do after that is INSERT a new row into the user table.

I hope this makes sense to you.
